trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet --info
  displayName: 'Show .NET info'

- script: cat StringExtensionsLib/StringExtensionsLib.csproj
  displayName: 'Show csproj'

- script: dotnet restore StringExtensionsLib/StringExtensionsLib.csproj
  displayName: 'Restore project'

- script: dotnet build StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

- script: dotnet pack StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Pack NuGet'
  
- task: NuGetAuthenticate@1
  displayName: 'Authenticate to Azure Artifacts'

- script: |
    ls $(Build.ArtifactStagingDirectory)
    dotnet nuget push "$(Build.ArtifactStagingDirectory)"/*.nupkg \
      --source "https://pkgs.dev.azure.com/YOUR_ORG/YOUR_PROJECT/_packaging/lab4-feed/nuget/v3/index.json" \
      --skip-duplicate
  displayName: 'Push to Artifacts'